export const WAZIRX_BTC_REQUEST = "WAZIRX_BTC_REQUEST";
export const WAZIRX_BTC_SUCCESS = "WAZIRX_BTC_SUCCESS";
export const WAZIRX_BTC_FAIL = "WAZIRX_BTC_FAIL";

export const CROSSTOWER_BTC_REQUEST = "CROSSTOWER_BTC_REQUEST";
export const CROSSTOWER_BTC_SUCCESS = "CROSSTOWER_BTC_SUCCESS";
export const CROSSTOWER_BTC_FAIL = "CROSSTOWER_BTC_FAIL";

export const ZEBPAY_BTC_REQUEST = "ZEBPAY_BTC_REQUEST";
export const ZEBPAY_BTC_SUCCESS = "ZEBPAY_BTC_SUCCESS";
export const ZEBPAY_BTC_FAIL = "ZEBPAY_BTC_FAIL";

export const COINDCX_BTC_REQUEST = "COINDCX_BTC_REQUEST";
export const COINDCX_BTC_SUCCESS = "COINDCX_BTC_SUCCESS";
export const COINDCX_BTC_FAIL = "COINDCX_BTC_FAIL";

export const USD_TO_INR_REQUEST = "USD_TO_INR_REQUEST";
export const USD_TO_INR_SUCCESS = "USD_TO_INR_SUCCESS";
export const USD_TO_INR_FAIL = "USD_TO_INR_FAIL";

export const MAIN_CARD_API_REQUEST = "MAIN_CARD_API_REQUEST";
export const MAIN_CARD_API_SUCCESS = "MAIN_CARD_API_SUCCESS";
export const MAIN_CARD_API_FAIL = "MAIN_CARD_API_FAIL";
